[package]
name = "mpvrun2"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
inquire = "0.7.5"
pyo3 = "0.26.0"
serde_json = "1.0.132"
